/**
 * Persona Client
 *
 * Fetches persona data and pre-generated conversational prompts
 * from the persona-builder service.
 *
 * Primary: Uses pre-generated conversational prompt (fast, no LLM call)
 * Fallback: Uses raw persona data + persona-prompt-builder to build a prompt
 */

import { buildPersonaSystemPrompt, type PersonaData } from '../agent/persona-prompt-builder.js';

/** Response from /api/personas/:id/conversational-prompt */
interface ConversationalPromptResponse {
  personaId: string;
  personaName: string;
  prompt: string;
  voiceId?: string | null;
}

/** Response from /api/personas/public/:id */
interface PublicPersonaResponse {
  persona: PersonaData & { id: string };
}

export interface PersonaInfo {
  id: string;
  name: string;
  tagline?: string;
  avatarUrl?: string | null;
  voiceId?: string;
}

export class PersonaClient {
  private baseUrl: string;

  constructor(baseUrl?: string) {
    this.baseUrl = (baseUrl || process.env.PERSONA_BUILDER_URL || 'http://localhost:4003').replace(/\/$/, '');
  }

  /**
   * Fetch the pre-generated conversational prompt for a persona.
   * This is the preferred method - returns a complete system prompt
   * that was generated by the prompt-generator during persona creation.
   */
  async fetchConversationalPrompt(personaId: string): Promise<{ prompt: string; personaName: string; voiceId?: string | null } | null> {
    console.log(`[PersonaClient] Fetching conversational prompt for: ${personaId}`);
    const startTime = Date.now();

    try {
      const response = await fetch(`${this.baseUrl}/api/personas/${personaId}/conversational-prompt`, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
      });

      if (!response.ok) {
        console.warn(`[PersonaClient] Conversational prompt not available (${response.status})`);
        return null;
      }

      const data = await response.json() as ConversationalPromptResponse;
      const duration = Date.now() - startTime;
      const voiceId = data.voiceId || null;

      console.log(`[PersonaClient] Raw API response voiceId field:`, data.voiceId);
      console.log(`[PersonaClient] Extracted voiceId: ${voiceId}`);

      if (voiceId) {
        console.log(`[PersonaClient] Fetched conversational prompt for "${data.personaName}" with voiceId: ${voiceId} in ${duration}ms`);
      } else {
        console.log(`[PersonaClient] Fetched conversational prompt for "${data.personaName}" but voiceId is null/undefined in ${duration}ms`);
      }

      return {
        prompt: data.prompt,
        personaName: data.personaName,
        voiceId: voiceId,
      };
    } catch (error) {
      console.error('[PersonaClient] Failed to fetch conversational prompt:', error);
      return null;
    }
  }

  /**
   * Fetch full public persona data.
   * Used as fallback when conversational prompt is not available.
   */
  async fetchPublicPersona(personaId: string): Promise<PublicPersonaResponse['persona'] | null> {
    console.log(`[PersonaClient] Fetching public persona data for: ${personaId}`);
    const startTime = Date.now();

    try {
      const response = await fetch(`${this.baseUrl}/api/personas/public/${personaId}`, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
      });

      if (!response.ok) {
        console.warn(`[PersonaClient] Public persona not found (${response.status})`);
        return null;
      }

      const data = await response.json() as PublicPersonaResponse;
      const duration = Date.now() - startTime;
      console.log(`[PersonaClient] Fetched persona "${data.persona.identity?.name}" in ${duration}ms`);

      return data.persona;
    } catch (error) {
      console.error('[PersonaClient] Failed to fetch public persona:', error);
      return null;
    }
  }

  /**
   * Get the best available system prompt for a persona.
   *
   * Strategy:
   * 1. Try fetching the pre-generated conversational prompt (fast, best quality)
   * 2. Fall back to building a basic prompt from raw persona data
   * 3. Return null if persona not found at all
   */
  async getPersonaSystemPrompt(personaId: string): Promise<{ prompt: string; personaInfo: PersonaInfo } | null> {
    // Strategy 1: Pre-generated conversational prompt (preferred)
    const conversationalPrompt = await this.fetchConversationalPrompt(personaId);
    if (conversationalPrompt) {
      const voiceId = conversationalPrompt.voiceId || undefined;
      if (voiceId) {
        console.log(`[PersonaClient] Extracted voiceId from conversational prompt: ${voiceId}`);
      } else {
        console.log(`[PersonaClient] No voiceId found in conversational prompt`);
      }
      return {
        prompt: conversationalPrompt.prompt,
        personaInfo: {
          id: personaId,
          name: conversationalPrompt.personaName,
          voiceId: voiceId,
        },
      };
    }

    // Strategy 2: Build from raw persona data
    console.log(`[PersonaClient] Falling back to raw persona data for prompt building`);
    const persona = await this.fetchPublicPersona(personaId);
    if (!persona) {
      console.error(`[PersonaClient] Persona ${personaId} not found`);
      return null;
    }

    // Use the dedicated persona-prompt-builder module
    const prompt = buildPersonaSystemPrompt(persona, {
      includeBackstory: true,
      emphasizeTraits: true,
      includeGaming: true,
    });

    const voiceData = persona.voice as { elevenLabsVoiceId?: string } | undefined;
    const voiceId = voiceData?.elevenLabsVoiceId;

    console.log(`[PersonaClient] Raw voice object from public persona:`, JSON.stringify(voiceData));
    console.log(`[PersonaClient] Extracted elevenLabsVoiceId: ${voiceId}`);

    if (voiceId) {
      console.log(`[PersonaClient] Extracted voiceId from raw persona data: ${voiceId}`);
    } else {
      console.log(`[PersonaClient] No voiceId found in raw persona data`);
    }

    return {
      prompt,
      personaInfo: {
        id: persona.id,
        name: persona.identity?.name || 'Unknown',
        tagline: persona.identity?.tagline,
        avatarUrl: persona.visualIdentity?.avatarUrl,
        voiceId: voiceId,
      },
    };
  }

  /**
   * Check if persona-builder service is reachable
   */
  async isAvailable(): Promise<boolean> {
    try {
      const response = await fetch(`${this.baseUrl}/health`, { method: 'GET' });
      return response.ok;
    } catch {
      return false;
    }
  }
}

// Singleton instance
export const personaClient = new PersonaClient();
